namespaceOverride: jenkins

controller:
  serviceType: LoadBalancer
  numExecutors: 2

persistence:
  enabled: false

agent:
  enabled: false
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    