namespaceOverride: jenkins

controller:
  serviceType: LoadBalancer

  installPlugins:
    - kubernetes:4557.ve746270f672f
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2121.v86fe99d4b_b_a_b_
    - terraform:1.0.10

persistence:
  enabled: false

agent:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    