namespaceOverride: jenkins

controller:
  serviceType: LoadBalancer
  JCasC:
    configScripts:
      create-pipeline-job: |
        jobs:
          - script: |
              folder('customer-A') {
                description("Pipelines for customer")
              }
              pipelineJob('customer-A/jenkinspipeline') {
                description('Pipeline for jenkinspipeline repository')

                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/anandambitionv2/jenkinspipeline.git')
                        }
                        branch('*/main')
                      }
                    }
                    scriptPath('JenkinsFile')
                    lightweight()
                  }
                }
              }

  installPlugins:
    - kubernetes:4557.ve746270f672f
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2121.v86fe99d4b_b_a_b_
    - terraform:1.0.10
    - job-dsl:3732.v9a_c49a_61a_313
    - pipeline-stage-view:2.41

persistence:
  enabled: true

agent:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"

additionalAgents:
  terraform:
    podName: mycustomtf
    customJenkinsLabels: mycustomtf
    sideContainerName: mycustomtf-sidecar
    image: 
      repository: hashicorp/terraform
      tag: "1.13.3"
    command: "/bin/sh -c"
    args: "cat"
    TTYEnabled: true